# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4e4462ef1d0c0daec242efd4ca74ff302f057666938836e4f04880b2c7ddfc3da255796bf4d8f5cd63a0e685ff3644ba1017c9fccf1b650f88e2952d8fc3698

test:
  secret_key_base: fc0fd852b17b8ad092e44d0cd7536f19c3cd98746cf41916a142363f656ffb8f0e7d1ce8631ae69d83ccb6e384dd1fa990623642d8bf17ede5c3df283dd84c30

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
